### ISSUE TITLE
Process suspends itself right away

### ISSUE THREAD

**Issue by brandonros** [websockets/wscat#20]
```
➜  f git:(master) ✗ wscat -c wss://ws.foo.com/socket.io/?EIO=3&transport=websocket
[2] 12476
➜  f git:(master) ✗
[2]  + 12476 suspended (tty output)  wscat -c wss://ws.foo.com/socket.io/?EIO=3
➜  f git:(master) ✗ fg
[2]  - 12476 continued  wscat -c wss://ws.foo.com/socket.io/?EIO=3
error: Error: unexpected server response (502)
> %
```

**Comment by esphen** [comment]
Try `wscat -c 'wss://ws.foo.com/socket.io/?EIO=3&transport=websocket'`.

& in bash has a special meaning, i.e. run in the background, when wrapping with single quotes you escape that meaning

**Comment by brandonros** [comment]
I'm sorry I'm so stupid.

**Comment by brandonros** [comment]
This is totally out of the scope of this project, but maybe somebody can help.

```
➜  f git:(master) ✗ wscat -c "wss://ws.f.com/socket.io/?EIO=3&transport=websocket"
connected (press CTRL+C to quit)
  < 0{"sid":"f","upgrades":[],"pingInterval":25000,"pingTimeout":60000}
```

```
WebSocket connection to 'wss://ws.f.com/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.
libraries.min.32df523….js:24 WebSocket connection to 'wss://ws.f.com/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_TIMED_OUT
```

Same machine, intermittent WebKit/Chrome issue it seems because wscat can connect. Any ideas?

**Comment by esphen** [comment]
I'm not sure what your problem is exactly? Are you disconnecting after some time because you are not being active with the server? In which case, have a look at [wsta](https://github.com/esphen/wsta/), a program like wscat that has a ping feature to keep the connection alive.

Is Chrome failing to connect, but wscat is working? Perhaps you need to have a closer look at your code and implementation socket.io. And yes, a question like that may be more appropriate on StackOverflow :)
